name: mdgp-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - rise
  - scipy
  - seaborn
  - ipywidgets
  - jupyter_contrib_nbextensions
  - ipyvolume
  - mshr
  - fenics
  - pandas
  - pulp
