name: mdgp-python
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - rise
  - scipy
  - seaborn
  - ipywidgets
  - jupyter_contrib_nbextensions
  - ipyvolume
  - mshr=2019.1.0=py38h255090a_2
  - fenics
  - pandas
  - pulp
