name: scientific-python
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  ..
     - pandas
     - bokeh
  - rise
  - scipy
  - seaborn
  - ipywidgets
  - jupyter_contrib_nbextensions
