name: mdgp-python
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - rise
  - scipy
  - seaborn
  - ipywidgets
  - jupyter_contrib_nbextensions
  - ipyvolume
  - mshr
  - fenics
  - pandas
  - pulp
  - bokeh
